### ISSUE TITLE
[Question] Is there any config that affect this library?

### ISSUE THREAD

**Issue by haiduong87** [golavr/SegmentDownloader#1]
Hi @golavr ,

I tried these libraries:
https://www.nuget.org/packages/SegmentDownloader.Protocol/
https://www.nuget.org/packages/SegmentDownloader.Core/

It worked on a tested solution. (I created my own based on the console sample)
But when I applied to my real project, it ran very slow.
I used same code, download same url.

I also tried: while the real project was downloading, I opened the tested one and ran. And the tested solution finished, while the real project ran forever... (I left office and leave it there)

Do you have any idea?

Thanks alot,

Duong Nguyen

**Comment by golavr** [comment]
The only thing i can think of is the configuration.
Make sure you add the configuration sections to your "real project" app.config.
