### ISSUE TITLE
Using PersistedListExtension to save current downloading list

### ISSUE THREAD

**Issue by mhd-karimi** [golavr/SegmentDownloader#2]
Hi @golavr,

Do you have any plans to add using extensions example to your console application or is there any other one?
I didn't understand adding UI namespace to extension classes!

Thanks,
Mohammad

**Comment by golavr** [comment]
@m-karimi  I totally agree with you
With that been said i forked this project
I did my best to decouple UI elements from:
SegmentDownloader.Core
SegmentDownloader.Protocol

Which are the ones i'm using and nuget maintain
SegmentDownloader.Protocol contain HTTP and FTP extensions(provider) which are used by the sample
