### ISSUE TITLE
Can you give example segment download with Pause Resume stop

### ISSUE THREAD

**Issue by l4km47** [golavr/SegmentDownloader#4]
please only need example for segment download with Pause Resume stop, and witch classes need to use  this too confusing

**Comment by augustocb23** [comment]
Hi, 
I was with the same problem, but I'd find the answer 😃 

### in memory
If you only want to pause temporaly, just call the `Pause all` method

```csharp
DownloadManager.Instance.PauseAll()
```

You can also pause each download using the `Downloads` list

```csharp
foreach (var downloader in DownloadManager.Instance.Downloads)
    downloader.Pause();
```

### persistent
But if you want to close the programm and restart the download after, you'll need to use the `PersistedListExtension` class, implemented in the Extensions package.

You can only copy the folder (without any other extensions). It implements the `IExtension`, but is not used any time and you can securely remove that interface and implementated method.

When open the application, instantiate the PersistedList and save it on a private property. Then, just look for paused downloads and start it...

```csharp
_persistedList = new PersistedListExtension();
if (DownloadManager.Instance.Downloads.Any())
    foreach (var downloader in DownloadManager.Instance.Downloads)
        downloader.Start();
```

When pause the downloads or finish it, you can save the state using the `dispose()` method. It will also call the `PauseAll()` method, but the `PersistedListExtension` already have a `TimerCallback` that saves the list every 120 seconds (you can change this time with the `SaveListIntervalInSeconds` constant.

```csharp
_persistedList.Dispose();
```

**Comment by augustocb23** [comment]
Hi guys,
I made a usage example using the PersistedList extension and hash validation.
https://github.com/augustocb23/Downloader
